version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
    ports:
      - 80:4000
    depends_on:
      - redis

  teal_cache_controller:
    build: ./teal_cache_controller
    volumes:
      - ./teal_cache_controller:/app
    depends_on:
      - gateway
