version: '3'

services:
  redis:
    image: redis
    #command: ["redis-server", "--bind", "redis", "port", "6379"]
    #container_name: redis
    #expose:
    #  - 6379
    ports:
      - 6379:6379

  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
    ports:
      - 4000:4000
    depends_on:
      - redis
