version: '3'

services:
  database:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: wjrh
      POSTGRES_PASSWORD: hogghall
 
  redis:
    image: redis
    ports:
      - 6379:6379

  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
    ports:
      - 80:4000
    depends_on:
      - redis

  teal_cache_controller:
    build: ./teal_cache_controller
    volumes:
      - ./teal_cache_controller:/app
    depends_on:
      - gateway

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000

  loki:
    image: grafana/loki
    restart: always
    ports:
      - 3100:3100
