version: '3'

services:
  database:
    image: postgres
    restart: always
    volumes:
     - "postgres-data:/var/lib/postgresql/data"
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: wjrh
      POSTGRES_PASSWORD: hogghall
 
  redis:
    image: redis
    ports:
      - 6379:6379

  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
    ports:
      - 80:4000
    depends_on:
      - redis

  teal_cache_controller:
    build: ./teal_cache_controller
    volumes:
      - ./teal_cache_controller:/app
    depends_on:
      - gateway

  grafana:
    build: ./custom-grafana
    restart: always
    volumes:
      - "grafana-lib:/var/lib/grafana"
      - "grafana-etc:/var/etc/grafana"
    ports:
      - 3000:3000


volumes:
  grafana-lib:
  grafana-etc:
  postgres-data:
