version: '3.4'

services:
# postgres sql database
  database:
    image: postgres
    restart: always
    volumes:
     - "postgres-data:/var/lib/postgresql/data"
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: wjrh
      POSTGRES_PASSWORD: hogghall
 
# redis
  redis:
    image: redis
    ports:
      - 6379:6379

  # graphql api gateway
  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
    ports:
      - 80:4000
    depends_on:
      - redis

  # grafana server
  grafana:
    build: ./custom-grafana
    restart: always
    volumes:
      - "grafana-lib:/var/lib/grafana"
      - "/var/lib/grafana/plugins"
      - "grafana-etc:/var/etc/grafana"
    ports:
      - 3000:3000
    environment:
      TZ: 'EST5EDT'

  scheduler:
    image: mcuadros/ofelia
    command: daemon --docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - clone-teal
    labels:
      ofelia.job-run.clone-teal.schedule: "@hourly"
      ofelia.job-run.clone-teal.image: "api_clone-teal"
      ofelia.job-run.clone-teal.command: "node index.js"

  clone-teal:
    build: ./clone-teal
    depends_on:
      - gateway

volumes:
  grafana-lib:
  grafana-etc:
  postgres-data:
