#!/usr/bin/node

const { Pool } = require('pg')
const pool = new Pool({
	user: 'wjrh',
	password: 'hogghall',
	host: 'api.wjrh.org',
	port: 5432,
	database: 'wjrh',
})

const prompt = require("prompt")

async function insert(args){
	// parse arguments
	shortname = args.shortname || ''
	program = args.shortname || ''
	season = args.shortname || ''
	year = args.shortname || ''
	start_time = args.shortname || ''
	end_time = args.shortname || ''

}

async function run(){
	const client = await pool.connect()
	const query = client.query(`
		SELECT * FROM schedule WHERE True;
	`)

	const result = await query
	console.log(result.rows[0])
	client.release()
}


console.log("test")
run()
